### ISSUE TITLE
Bit rate

### ISSUE THREAD

**Issue by gavia** [KayLerch/alexa-meets-polly#1]
In your latest commit you've claimed that you don't need to convert the MP3 to the correct bitrate anymore, but that's not the case as far as I can tell. Can you explain why this is the case?

**Comment by lucyskidmore** [comment]
I would also like to know the answer to this! @gavia did you get any further in finding out?

**Comment by KayLerch** [comment]
Sorry for my late answer. It is indeed true. The code you can find in this repo works in production for one of the most used Alexa skills in Germany just in case you need reference :)
The most important thing is you should not touch the mp3 you receive from Polly (e.g. with ffmpeg) but rather store it as received and link to it in your SSML. Please follow the parameters of your Polly request as seen here: https://github.com/KayLerch/alexa-meets-polly/blob/master/skill/src/main/java/io/klerch/alexa/translator/skill/tts/TextToSpeechConverter.java#L145

**Comment by lucyskidmore** [comment]
Hi Kay, 

Thanks very much for your response. Unfortunately, this approach still isn't working for me. I must be missing something...

Here is my example of trying to synthesise the Japanese word 'konnichiwa' inside my LaunchRequestHandler: 

`const LaunchRequestHandler = {
    canHandle(handlerInput) {
        return handlerInput.requestEnvelope.request.type === 'LaunchRequest';
    },
    
    handle(handlerInput) {
        
        
        var text_params = {
            OutputFormat: 'mp3',
            Text: "<speak><amazon:effect name='drc'><prosody rate='-15%' volume='x-loud'> こんにちは </prosody></amazon:effect><break time='250ms' /></speak>",
            VoiceId: 'Mizuki',
            SampleRate: '16000', 
            TextType: 'ssml'
            };
                
                
        polly.synthesizeSpeech(text_params, function(err, data) {
            if (err) {
              console.log(err, err.stack);
            } else {
              console.log(data);
              var s3_params = {
              Body: data.AudioStream,
              Bucket: 'inaflashaudio',
              Key: "new.mp3"
              };
              s3.putObject(s3_params, function(err, data) {
              if (err) {
                console.log(err, err.stack);
                }else{
                  console.log(data);    
                }         
              });     
            }
        });
                
        
        const speechText ="<audio src='https://s3-eu-west-1.amazonaws.com/inaflashaudio/new.mp3'/>";
        
        return handlerInput.responseBuilder
        .speak(speechText)
        .reprompt()
        .getResponse();
  }
};`

When testing this in the developer console the response from Alexa is 'I am having trouble connecting to the audio file U.R.I.' 

Any feedback from you would be appreciated - thanks!

Lucy

**Comment by KayLerch** [comment]
Two things:
1) Set the sample rate to 22050. Disregard the settings given in the developer docs, it works, believe me.
2) When you‘re writing the file to S3 make sure to set the PublicRead option as otherwise Alexa cannot access it.

Good luck!

**Comment by gavia** [comment]
So I'm pretty sure that's exactly what I did but to no avail. Anyway, @lucyskidmore if you can't get it to work I found a work around. Essentially, I wrote a lambda (bundled with ffmpeg) to convert the output from Polly into something that Alexa would be able to play. Let me know if you want the code.

**Comment by lucyskidmore** [comment]
It's working! 
Thank you so much for both of your help :) I'll put the final version of my skill on here once it's finished if you're interested in having a look. 

Thanks again!

**Comment by KayLerch** [comment]
Hey Lucy,

glad to hear it now works for you. Would you like to share with the community what did the trick?

Looking forward to see what you built.

**Comment by lucyskidmore** [comment]
Absolutely! I implemented the two changes that you suggested, so my call to Polly ended up looking like this: 

`    var text_params = {
        OutputFormat: 'mp3',
        Text: "<speak><amazon:effect name='drc'><prosody rate='-15%' volume='x-loud'>こんにちは</prosody></amazon:effect><break time='250ms' /></speak>",
        VoiceId: 'Mizuki',
        SampleRate: '22050', 
        TextType: 'ssml'
        };
    
    polly.synthesizeSpeech(text_params, function(err, data) {
        if (err) {
          console.log(err, err.stack);
        } else {
          console.log(data);
          var s3_params = {
          Body: data.AudioStream,
          Bucket: 'inaflashaudio',
          Key: mp3, 
          ACL: 'public-read'
          };
          s3.putObject(s3_params, function(err, data) {
          if (err) {
            console.log(err, err.stack);
            }else{
              console.log(data);    
            }         
          });     
        }
    });`

Thanks again! I'll be sure to share on here when my project is finished :)

**Comment by KayLerch** [comment]
Thanks for sharing. Closing now.
